default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  database: parking_management_api_development

test:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  database: parking_management_api_test

production:
  <<: *default
  url:  <%= ENV["DB_URL"] %>