default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: parking_management_api_development

test:
  <<: *default
  database: parking_management_api_test

production:
  <<: *default
  database: parking_management_api_production
